language: python
python:
- 2.7
install:
- pip install tox-travis
script:
- tox
notifications:
  slack:
    secure: I4LJEJ5Mc81NaNiWdKwhIAIikVfsGCszL6JOmCCJYthuUkirB6KdJFX5XkSOgFmLb1bqCeSHu5cG3tMMDjs3l1uhdMbL4rxLDzac3QF30mXsAYrdnwScfRitQ2TlogF7zMMXHUy8mmtdLU49a/ua9lhNyWROmZDKsClgT7/FP+htg7pxsgCl4nWWVy8FWj/i3u8jpJ+xAv08KY7t6LBX/dHEedyS6S304urgEKpg+do4+fGlplCw84HOHgy3XfX42oUFZn05Pp3rWySo472ttGM9Nx0dba8h67fk5v9zPqc3TYH6SwqH80mngpoA+o7J71Qp2gNBUBH0NWy4oBdrXruuaj2gC+fZXHsW69neG8Xglp5mtNageUkvxhv1PVtbmYX3UenEXMrUgvfEXOhCk7nz7xEe+pykbFMTk3SGf0Ys21y0+W+fmQ/F/nDIDTzNd6rkWb+R3hnIotNQ3lR6XFGErhYmMqoooBmUiTqKRzLYBNXi6XMQ7ma9h+Egr6E6maL+C55kztxM5AToXFfq7+U+XgWBCfHWXGLDVobj7vfQtsupSNhhU0L10yweh4DVY8p+91/hEHK+lewYBOKAvUyaWTJOUo51Z4DQ8Arfj5q0fRRO9iyWB6PHdf1o1uNMWQvAp5MiyS3pP/rLiEs5mc8IjHeWMMm6l/0Y9r3xewE=
