# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_create_review_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richtextpage',
            name='intro',
        ),
    ]
