# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_richtextpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcarouselitem',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='eventpagecarouselitem',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselitem',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='reviewpagecarouselitem',
            name='embed_url',
        ),
        migrations.RemoveField(
            model_name='richtextpagecarouselitem',
            name='embed_url',
        ),
    ]
