# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_gallery_gallerycollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycollection',
            name='videos',
            field=wagtail.wagtailcore.fields.StreamField([('video', wagtail.wagtailembeds.blocks.EmbedBlock(icon='media'))], default=''),
            preserve_default=False,
        ),
    ]
